version: '3.8'

services:
  vector-db-api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - LOG_LEVEL=INFO
      - PERSISTENCE_TYPE=file
      - DATA_DIRECTORY=/app/data
      - COHERE_API_KEY=${COHERE_API_KEY}
    volumes:
      - ./data:/app/data  # For persistent storage if needed
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 